from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import matplotlib.pyplot as mtp
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler  
from sklearn.naive_bayes import GaussianNB  
from sklearn.metrics import confusion_matrix  